### PR TITLE
Less ramda

### PR DESCRIPTION
**Pull request by christian-hawk**

### CODE REVIEW

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
@kdhttps testing in my fork

**Comment by christian-hawk** [comment]
run test

**Comment by christian-hawk** [comment]
run tests

**Comment by kdhttps** [comment]
Sorry not getting you. Do you want me to run test cases ?

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Pull request merged**
